- name: debug message                    
  debug:
    msg: "this is {{ name }}"
- debug:
    msg: "this is {{ age }}"

- debug:
    msg: "this is {{ city }}"

- debug:
    msg: "this is {{ clg }}"

- debug:
    msg: "this is {{ Edu }}"

####  using apt module install nginx

- name: Install a list of packages
  apt:
    name:
      - nginx
      - postgresql
    state: present
  