# -
#   name: Play1
#   hosts: localhost
#   tasks:
#     - name: "checking working directory"
#       command: pwd chdir=/root
#       register: result
#     - debug: msg="{{ result.stdout }}"


# create a directory
# -
#   name: Play1
#   hosts: localhost
#   tasks:
#     - name: "creating directory"
#       command: mkdir /home/insigniac-arpit/Desktop/workspace/ansible-test creates=/home/insigniac-arpit/Desktop/workspace/ansible1.test
#       register: result
#     - debug: msg="{{ result.stdout }}"

# copy a file into a directory  
-
  name: Play1
  hosts: localhost
  tasks:
    - name: "creating directory"
      command: touch copy-test.log chdir= /home/insigniac-arpit/Desktop/workspace/ansible-test creates=/home/insigniac-arpit/Desktop/workspace

-
  name: Play2
  hosts: localhost
  tasks:
    - name: "creating file"
      copy: scr=/home/insigniac-arpit/Desktop/workspace/test.log dest=/home/insigniac-arpit/Desktop/workspace/ansible1-test/